BooksBundle\Entity\Library:
    type: entity
    table: library
    repositoryClass: BooksBundle\Repository\LibraryRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: typeSupport
        type: string
    discriminatorMap:
        book: BooksBundle\Entity\Book
        comic_strip: BooksBundle\Entity\ComicStrip
        ebook: BooksBundle\Entity\Ebook

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        type:
            type: string
        title:
            type: string
            length: 200
        author:
            type: string
            length: 100
        cycle:
            type: string
            length: 200
            nullable: true
        resume:
            type: text
        detention:
            type: boolean
        isbn_10:
            type: integer
            nullable: true
        isbn_13:
            type: integer
            nullable: true
        publishedDate:
            type: datetime
            nullable: true
        pageCount:
            type: integer
            nullable: true
        language:
            type: string
            length: 50
            nullable: true
        editor:
            type: string
            length: 100
            nullable: true

BooksBundle\Entity\Book:
    type: entity

BooksBundle\Entity\ComicStrip:
    type: entity

BooksBundle\Entity\Ebook:
    type: entity



